from . import review
from . import address
from . import edit_address
from . import order
from . import order_confirmation
from . import SelectedFood
from . import restaurant
from . import promotion
from . import qrcode_payment
from . import profile
from . import mycart
from . import favorite
from . import account_management
from . import location
from . import Homepage
from . import delivery
from . import dessert
from . import sidedish
